name: Cypress Regression Tests

on: [push]

jobs:

  ui-chrome-tests:
    runs-on: ubuntu-latest #Cria uma instância do ubunto com o chrome instalado
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false #Continuar a execução mesmo que um bug seja encontrado
    steps:
      - name: Checkout #Obtém uma cópia do código fonte cypress que está no repositório e insere dentro do Contêiner (ubuntu-latest)
        uses: actions/checkout@v2
      
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2 #Plugin oficial para testar com cypress dentro do GitHub Actions
        with:
          install-command: yarn install
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: 'UI - Chrome'
          spec: cypress/integration/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
